config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'users/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'users/add_users' => 'users#add_users'

  get 'contracts/new'
  get 'contracts/index'
  get 'contracts/:id/:link(.:format)', to: 'contracts#show', as: 'contracts_show'
  post 'contracts' => 'contracts#create'
  post 'contracts/update' => 'contracts#update'
  delete 'contracts/delete', to: 'contracts#destroy', as: 'contracts_delete'
  get 'contracts/invite_users' => 'contracts#invite_users', as: 'contracts_invite'

  post 'answers/edit/all' => 'answers#edit_all', as: :answers_edit_all
  get 'answers/new', to: 'answers#new', as: 'new_answers'
  get 'answers/index'
  post 'answers' => 'answers#create'

  get 'decisions/new'
  get 'decisions/index'
  get 'decisions/edit' => 'decisions#edit'
  get 'decisions/show' => 'decisions#show'
  post 'decisions/edit' => 'decisions#update'
  post 'decisions/new' => 'decisions#create'
  delete 'decision/delete' => 'decisions#destroy'

end

app/models/decision.rb
class Decision < ApplicationRecord
  validates :contract_id, presence: true
  validates :description, presence: true

  has_many :answers, :dependent => :destroy
  belongs_to :contract

  # this is used to pre-check radio_button on answer modal
  def user_answer_type?(type, user)
      self.answers.exists?(answer: type, user: user)
  end

end

app/controllers/decisions_controller.rb
class DecisionsController < ApplicationController
  before_action :find_decision, only: [:edit, :destroy]

  def new
    @decision = Decision.new(:contract_id => session[:contract_id])
  end

  def create
    @decision = Decision.new(decision_params)
    @contract = @decision.contract
    if @decision.save
      redirect_to @contract.path
    else
      render decisions_new_path(@decision)
    end
  end

  def edit
  end

  def update
    @decision = Decision.find(decision_params[:id])
    @contract = @decision.contract
    if @decision.update(:description => decision_params[:description])
      redirect_to @contract.path
    end
  end

  def destroy
    @contract = @decision.contract
    @decision.destroy
    redirect_to @contract.path
  end


private
  def find_decision
    @decision = Decision.find(params[:decision_id])
  end

  def decision_params
    params.require(:decision).permit(:description, :contract_id, :id)
  end
end

app/helpers/decisions_helper.rb
module DecisionsHelper
end

app/views/decisions/_decision_menu.html.erb
<div class="dropdown">
  <!-- dropdown btn  -->
  <div class="col-xs-2" id="desc_dropdown_btn" data-toggle="dropdown" >
    <a type="link" class="btn-primary btn-sm dropdown-button text-center"><nobr><%= decision.description %></nobr></a>
  </div>
  <!-- dropdown menu  -->
  <ul class="dropdown-menu" id="desc_dropdown">
    <% wording = Answer.find_by(decision: decision.id, user: current_user) ? "Change Answer" : "Answer" %>
    <li><%= link_to "#{wording}", new_answers_path(:decision_id => decision) %></li>
    <% if @owner %>
      <li> <div class="text-left menu_break">Owner</div></li>
      <li><%= link_to "Edit", decisions_edit_path(:decision_id => decision) %></li>
      <li><%= link_to 'Delete', decision_delete_path(:decision_id=> decision.id), method: 'delete', data: {:confirm => 'Are you sure?'} %></li>
    <% end %>
  </ul>
</div>

app/views/decisions/_decision_menu_or_text.html.erb
<% if !decision.contract.complete && @viewer == false %>
  <%= render 'decisions/decision_menu', :decision => decision, :@owner => @owner %>
<% else %>
  <%= decision.description %>
<% end %>

app/views/decisions/_desktop_show.html.erb
<table class="table" data-toggle="table">
  <thead>
    <tr>
      <th class="col-xs-2">Decision</th>
      <th class="col-xs-2">Explain</th>
      <th class="col-xs-2">Consult</th>
      <th class="col-xs-2">Agree</th>
      <th class="col-xs-2">Advise</th>
      <th class="col-xs-2">Inquire</th>
    </tr>
  </thead>
  
  <tbody>
    <% @decisions.each do |decision| %>
      <tr>
        <th> <%= render 'decisions/decision_menu_or_text',:decision => decision, :@viewer => @viewer %> </th>
        <% if decision.answers %>
          <% Answer.types.each do |type| %><td><%= Answer.find_all_names(type, decision.answers, @user) %></td><% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/decisions/_form.html.erb
<div class="mx-auto container max-width-500">
  <%= render 'shared/form_errors', object: @decision %>
  <%= form_for :decision do |f| %>
    <div class="form-group">
      <%= f.label :description %><br>
      <%= f.text_field :description, placeholder: "Decision Text", required: "true", class: "form-control" %>
    </div>
    <%= f.hidden_field :contract_id, :value => @decision.contract_id %>
    <% if @decision %> <%= f.hidden_field :id, :value => @decision.id %> <%end%>
    <%= f.submit class: "btn btn-primary" %>
    <%= link_to "Cancel", @decision.contract.path, :class => "btn btn-danger"%>
  <% end %>
</div>

app/views/decisions/_mobile_show.html.erb
<div class="decisions-mobile-show">
  <% @decisions.each do |decision| %>
    <div class="row decision-card">
      <div class="col-xs-12 text-center description"><%= decision.description %></div>

      <% Answer.types.each do |type| %>
        <div class="answer-row col-xs-12">
          <div class=" col-xs-4 type text-left"><%= type %></div>
          <div class=" col-xs-8 text-right"><%= Answer.find_all_names(type, decision.answers, @user) %></div>
        </div>
      <% end %>

      <div class="decision-options mx-auto">
        <% wording = Answer.find_by(decision: decision.id, user: current_user) ? "Change Answer" : "Answer" %>
        <%= link_to "#{wording}", new_answers_path(:decision_id => decision), class: "btn btn-sm btn-primary" %>
        <% if @owner %>
          <%= link_to "Edit", decisions_edit_path(:decision_id => decision), class: "btn btn-sm btn-primary" %>
          <%= link_to 'Delete', decision_delete_path(:decision_id=> decision), method: 'delete', class: "btn btn-sm btn-danger", data: {:confirm => 'Are you sure?'} %>
        <% end %>
      </div>

    </div>
  <% end %>
</div>

app/views/decisions/_show.html.erb
<div class="container">
  <div id="decisions-show"></div>
</div>


<script>
$( document ).on('turbolinks:load', mobileOrDesktop)
$( document ).on('turbolinks:load', window.addEventListener("resize", mobileOrDesktop) )
function mobileOrDesktop() {
  if ($(window).width() < 768) {
    $('#decisions-show').html('<%=j render "decisions/mobile_show" %>');
  } else {
    $('#decisions-show').html('<%=j render "decisions/desktop_show" %>');
  }
};
</script>

app/views/decisions/_table.html.erb
<div class="row col-xs-10 col-xs-offset-1 col-xs-offset-right-1" style="border-bottom: 1px solid black">
  <div class="row">
    <div class="col-xs-2">Decision</div>
    <div class="col-xs-2">Explain</div>
    <div class="col-xs-2">Consult</div>
    <div class="col-xs-2">Agree</div>
    <div class="col-xs-2">Advise</div>
    <div class="col-xs-2">Inquire</div>
  </div>
</div>

app/views/decisions/edit.html.erb
<h1 class="text-center">Edit Decision</h1>
<%= render 'form' %>

app/views/decisions/new.html.erb
<h1 class="text-center">New Decision</h1>
<%= render 'form' %>