config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'users/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'users/add_users' => 'users#add_users'

  get 'contracts/new'
  get 'contracts/index'
  get 'contracts/:id/:link(.:format)', to: 'contracts#show', as: 'contracts_show'
  post 'contracts' => 'contracts#create'
  post 'contracts/update' => 'contracts#update'
  delete 'contracts/delete', to: 'contracts#destroy', as: 'contracts_delete'
  get 'contracts/invite_users' => 'contracts#invite_users', as: 'contracts_invite'

  post 'answers/edit/all' => 'answers#edit_all', as: :answers_edit_all
  get 'answers/new', to: 'answers#new', as: 'new_answers'
  get 'answers/index'
  post 'answers' => 'answers#create'

  get 'decisions/new'
  get 'decisions/index'
  get 'decisions/edit' => 'decisions#edit'
  get 'decisions/show' => 'decisions#show'
  post 'decisions/edit' => 'decisions#update'
  post 'decisions/new' => 'decisions#create'
  delete 'decision/delete' => 'decisions#destroy'

end

app/models/contract.rb
class Contract < ApplicationRecord
  validates :title, presence: true
  validates :link, presence: true
  validates :owner_link, presence: true
  validates :viewer_link, presence: true
  # validates :user_id, presence: true

  has_many :decisions, :dependent => :delete_all
  has_many :user_contracts, :dependent => :delete_all
  has_many :users, through: :user_contracts
  belongs_to :creator, :class_name => 'User'

  def owner?(user)
    self.user_contracts.exists?(owner: true, user_id: user.id, contract_id: self.id)
  end

  def collaborator?(user)
    self.user_contracts.exists?(owner:false, viewer: false, user_id: user.id, contract_id: self.id)
  end

  def viewer?(user)
    self.user_contracts.exists?(viewer: true, user_id: user.id, contract_id: self.id)
  end

  def self.find_which_by(params)
    Contract.find_by_link(params) || Contract.find_by_owner_link(params) || Contract.find_by_viewer_link(params)
  end

  def set_user_contract(hash_link, user)
    if hash_link == self.owner_link
      self.set_owner(user)
    elsif hash_link == self.link
      UserContract.find_or_create_by(user_id: user.id, contract_id: self.id)
    elsif hash_link == self.viewer_link
      UserContract.find_or_create_viewer(user, self)
    end
  end

  def toggle_task(task)
    if task == "review"
      self.toggle_review
    elsif task == "complete"
      self.toggle_complete
    end
  end

  def toggle_complete
    self.toggle(:complete)
  end

  def toggle_review
    self.toggle(:reviewable)
  end

  def self.find_by_link(params)
    Contract.find_by(id: params[:id], link: params[:link])
  end

  def self.find_by_owner_link(params)
    Contract.find_by(id: params[:id], owner_link: params[:link])
  end

  def self.find_by_viewer_link(params)
    Contract.find_by(id: params[:id], viewer_link: params[:link])
  end

  def user_list(current_user)
    user_list = []
    self.users.each do |user|
      user == current_user ? user_list.push("You") : user_list.push(user.users_name.chomp("."))
    end
    return user_list.join(", ")
  end

  def path
    return "/contracts/#{self.id}/#{self.link}"
  end

  def set_owner(user)
    if @user_contract = UserContract.where(user_id: user.id, contract_id: self.id).first
      @user_contract.update(owner: true)
    else
      UserContract.create_owner_join(user, self)
    end
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  include ContractsHelper
  before_action :require_login

  def new
    @contract = Contract.new
  end

  def create
    @contract = Contract.new(contract_params)
    @contract = add_links(@contract)
    @contract.creator = current_user
    if @contract.save
      UserContract.create_owner_join(current_user, @contract)
      redirect_to @contract.path
    else
      @error_messages = @contract.errors.full_messages
      render 'contracts/new'
    end
  end

  def update
    @contract = Contract.find_by(id: params[:id], owner_link: params[:link])
    @contract.toggle_task(params[:task])
    @contract.save
    if params[:refresh] == "false"
      redirect_to root_path
    else
      redirect_to @contract.path
    end
  end

  def show
    @contract = Contract.find_which_by(params)
    @contract.set_user_contract(params[:link], current_user)
    @owner = @contract.owner?(current_user)
    @viewer = @contract.viewer?(current_user)
  end

  def destroy
    Contract.find(params[:contract_id]).destroy
    redirect_to root_path
  end

  def invite_users
    @contract = Contract.find(params[:id])
    render 'contracts/invite_users'
  end

  private
  def contract_params
    params.require(:contract).permit(:title, :theme, :creator_id)
  end

end

app/helpers/contracts_helper.rb
module ContractsHelper

  def add_links(contract)
    p "+++++++++ Whoah add_links is working.. ++++++++++++"
    contract.link = SecureRandom.urlsafe_base64(5, false)
    contract.owner_link = SecureRandom.urlsafe_base64(5, false)
    contract.viewer_link = SecureRandom.urlsafe_base64(5, false)
    return contract
  end

end

app/views/contracts/_button.html.erb
<nobr>
  <p>
    <span class="hidden-sm hidden-xs"><b>Team Link:</b>/contracts/<%=@contract.id%>/<%=@contract.link%></span>
    <span class="hidden-md hidden-lg hidden-xl"><b>Team Link</b></span>

    <button class="btn btn-xs clip" data-clipboard-text="<%="#{request.protocol}#{request.host_with_port}"%>/contracts/<%=@contract.id%>/<%=@contract.link%>">
      <%= image_tag("clippy.svg", size: "15x15")%>
    </button>
  </p>
</nobr>

app/views/contracts/_collab_dashboard_show.html.erb
<div class="contract_link_box grid-item">
  <div class="contract_card">

    <div class="contract_card_header">
      <div class="collab_icons">
        <% if @contract.complete %>
          <i class='fa fa-lg fa-lock' aria-hidden='true'></i>
        <% else %>
          <i class='fa fa-lg fa-unlock-alt' aria-hidden='true'></i>
        <% end %>

        <% if @contract.reviewable %>
           <i class='fa fa-lg fa-users' aria-hidden='true'></i>
        <% else %>
          <i class='fa fa-lg fa-user' aria-hidden='true'></i>
        <% end %>
      </div>
      <p class="title_text">
        <a href="<%= "/contracts/#{@contract.id}/#{@contract.link}" %>">
          <%= @contract.title %>
        </a>
      </p>
      <p class="theme_text"><%= @contract.theme %></p>
      <hr>
    </div>

    <div class="contract_card_body">
      <p class="collaborators_text">On this contract:</p>
      <span class="user_list">
        <%= @contract.user_list(current_user) %>
      </span>
    </div>

    <!-- <hr>
    <div class="contract_card_footer">
    </div> -->

  </div>
</div>

app/views/contracts/_lg_new_button.html.erb
<%= link_to '<button type="button" class="btn btn-primary btn-lg col-xs-8 col-xs-offset-2">New Contract</button>'.html_safe, contracts_new_path %>

app/views/contracts/_link.html.erb
<!-- <nobr>
  <p>
    <span class="hidden-sm hidden-xs"><b>Team Link:</b>/contracts/<%=@contract.id%>/<%=@contract.link%></span>
    <span class="hidden-md hidden-lg hidden-xl"><b>Team Link</b></span> -->
    <!-- button to copy link -->
    <!-- <button class="btn btn-xs clip" data-clipboard-text="<%="#{request.protocol}#{request.host_with_port}"%>/contracts/<%=@contract.id%>/<%=@contract.link%>">
      <%= image_tag("clippy.svg", size: "15x15")%>
    </button>
  </p>
</nobr> -->

<a class="clip dropdown-item" data-clipboard-text="<%="#{request.protocol}#{request.host_with_port}"%>/contracts/<%=@contract.id%>/<%=@contract.link%>">
  Copy Collaborator Link
</a>

app/views/contracts/_new_modal.html.erb
<!-- Modal -->
<div class="modal-dialog" id="new_contract_modal">
  <div class="modal-content">
    <!-- modal header -->
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">New Contract</h4>
      <% if @error_messages %>
        <% @error_messages.each do |err| %>
          <p class="text-danger"><%= err %></p>
        <% end %>
      <% end %>
    </div>
    <!-- modal body -->
    <div class="modal-body">
      <div class="form">
        <%= form_for :contract, id: "contract_form", url: contracts_path do |f| %>
          <div class="form-group">
            <%= f.label :title %><br>
            <%= f.text_field :title, placeholder: "Contract Title", class: "form-control", required: true, autofocus: true %>
          </div>
          <div class="form-group">
            <%= f.label :theme %><br>
            <%= f.text_field :theme, placeholder: "Contract Theme", class: "form-control" %>
          </div>
          <div class="text-right"><%= f.submit class: "btn btn-primary"%></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/contracts/_owner_button.html.erb
<nobr>
  <p>
    <span class="hidden-sm hidden-xs"><b>Owner Link:</b>/contracts/<%=@contract.id%>/<%=@contract.owner_link%></span>
    <span class="hidden-md hidden-lg hidden-xl"><b>Owner Link</b></span>

    <button class="btn btn-xs clip" data-clipboard-text="<%="#{request.protocol}#{request.host_with_port}"%>/contracts/<%=@contract.id%>/<%=@contract.owner_link%>">
      <%= image_tag("clippy.svg", size: "15x15")%>
    </button>
  </p>
</nobr>

app/views/contracts/_owner_buttons.html.erb
<div class="button_container col-sm-12">
  <div class="buttons">

    <%= link_to "<i class='fa fa-user-plus fa-2x btn btn-primary'></i>".html_safe, contracts_invite_path(:id=>@contract)  %>

    <% @contract.reviewable ? @user_icon = "fa-users" : @user_icon = "fa-user" %>
    <% @contract.complete ? @lock_icon = "fa-lock" : @lock_icon = "fa-unlock-alt" %>
    <%= link_to "<i class='fa fa-2x btn btn-primary #{@user_icon}' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"review"), :method=>:post  %>
    <%= link_to "<i class='fa fa-2x btn btn-primary #{@lock_icon}' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"complete"), :method=>:post  %>
    <%= link_to "<i class='fa  fa-2x fa-trash-o btn btn-danger'  aria-label='Delete'></i>".html_safe, contracts_delete_path(:contract_id=>@contract.id ), :method => :delete, :data => {:confirm => 'Are you sure?'} %>
  </div>
</div>

app/views/contracts/_owner_dashboard_show.html.erb
<div class="contract_link_box grid-item">
  <div class="contract_card" id="<%= @contract.id %>">

    <div class="contract_card_header">
      <p class="title_text">
        <a href="<%= "/contracts/#{@contract.id}/#{@contract.link}" %>">
          <%= @contract.title %>
        </a>
      </p>
      <p class="theme_text"><%= @contract.theme %></p>
      <hr>
    </div>

    <div class="contract_card_body">
      <p class="collaborators_text">On this contract:</p>
      <span class="user_list">
        <%= @contract.user_list(current_user) %>
      </span>
    </div>

    <hr>

    <div class="contract_card_footer">
      <div class="button_container">
          <% if @contract.reviewable %>
            <%= link_to "<i class='fa fa-users' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"review", :refresh => "false"), :method=>:post, :class=>"btn btn-primary" %>
          <% else %>
            <%= link_to "<i class='fa fa-user' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"review", :refresh => "false"), :method=>:post, :class=>"btn btn-primary" %>
          <% end %>
          <% if @contract.complete %>
              <%= link_to "<i class='fa fa-lock' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"complete", :refresh => "false"), :method=>:post, :class=>"btn btn-primary unlock" %>
          <% else %>
            <%= link_to "<i class='fa fa-unlock-alt' aria-hidden='true'></i>".html_safe, contracts_update_path(:id=>@contract.id, :link=>@contract.owner_link, :task=>"complete", :refresh => "false"), :method=>:post, :class=>"btn btn-primary" %>
          <% end %>
          <%= link_to "<i class='fa fa-trash-o' aria-label='Delete'></i>".html_safe, contracts_delete_path(:contract_id=>@contract.id ), :method => :delete, :class => "btn btn-danger", :data => {:confirm => 'Are you sure?'} %>
      </div>
    </div>
  </div>
</div>

app/views/contracts/_viewer_buttons.html.erb
<div class="button_container col-sm-12">
  <div class="status_icons">
    <% @contract.reviewable ? @user_icon = "fa-users" : @user_icon = "fa-user" %>
    <% @contract.complete ? @lock_icon = "fa-lock" : @lock_icon = "fa-unlock-alt" %>
    <i class='fa fa-2x <%=@user_icon%>' aria-hidden='true'></i>
    <i class='fa fa-2x <%=@lock_icon%>' aria-hidden='true'></i>
  </div>
</div>

app/views/contracts/index.html.erb
<h1><%=@contract.title%><h1>

app/views/contracts/invite_users.html.erb
<div class="container invite_users">
  <h4 class="text-center"><%= @contract.title %></h4>

  <form action="/users/add_users" id="add_user_form" method="post">
      <input type="text" id="contract_id" name="contract_id" hidden="true" value="<%= @contract.id %>"  >
      <input class="form-control form-email" autofocus id="0-email" type="email" name="email_0" placeholder="Email" required autocomplete="off">
      <div class="radio-buttons">
        <input type="radio" id="0-collab" name="position_0" value="collab" checked> Collaborator
        <input type="radio" id="0-owner" name="position_0" value="owner"> Owner
        <% if @contract.viewer_link %>
          <input type="radio" id="0-viewer" name="position_0" value="viewer"> Viewer
        <% end %>
      </div>
      <div class="btn btn-primary add-user-btn" id="jsAddUser" >Add Another User</div>
      <div>
        <input class="btn btn-primary" type="submit" name="submit">
        <%= link_to "Cancel", @contract.path, :class => "btn btn-danger"%>
      </div>
  </form>
</div>
<!-- notes -->


<%=javascript_include_tag('add_users_modal.js')%>

app/views/contracts/new.html.erb
<div class="container">
  <h1 class="text-center">New Contract</h1>

  <div class="container mx-auto max-width-500">
    <% if @error_messages %>
      <% @error_messages.each do |err| %>
        <p class="text-danger"><%= err %></p>
      <% end %>
    <% end %>``
    <%= form_for :contract, url: contracts_path do |f| %>

      <div class="form-group">
        <%= f.label :title %><br>
        <%= f.text_field :title, placeholder: "Contract Title", class: "form-control", autofocus: true %>
      </div>

      <div class="form-group">
        <%= f.label :theme %><br>
        <%= f.text_field :theme, placeholder: "Contract Theme", class: "form-control" %>
      </div>

      <%= f.submit class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/contracts/show.html.erb
<% session[:contract_id] = @contract.id %>
<div class="container">
  <div class="row contract-header">
      <div class="col-sm-12 text-center">
        <h2><%= @contract.title %></h2>
        <p><%= @contract.theme %></p>
      </div>
      <% if @owner %>
        <%= render 'contracts/owner_buttons', :@contract => @contract %>
      <% else %>
        <%= render 'contracts/viewer_buttons', :@contract => @contract %>
      <% end %>
  </div>

  <% if @contract.decisions %>
      <%= render 'decisions/show', :@decisions => @contract.decisions.order('id'), :@user => current_user, :@owner => @owner, :@viewer => @viewer %>
  <% end %>

  <% if @viewer %>
    <h2 class="text-center" style="margin-top: 100px">Viewing Permissions Only.</h2>
  <% else %>
  <div class="text-center">
    <%= link_to "Add Decision", decisions_new_path(), :class => "btn btn-primary btn-lg"%>
  </div>
  <% end %>

</div>