config/routes.rb
Rails.application.routes.draw do

  get 'home/index'
  root 'home#index'

  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }
  get 'users/dashboard', to: 'users#dashboard', as: 'user_dashboard'
  post 'users/add_users' => 'users#add_users'

  get 'contracts/new'
  get 'contracts/index'
  get 'contracts/:id/:link(.:format)', to: 'contracts#show', as: 'contracts_show'
  post 'contracts' => 'contracts#create'
  post 'contracts/update' => 'contracts#update'
  delete 'contracts/delete', to: 'contracts#destroy', as: 'contracts_delete'
  get 'contracts/invite_users' => 'contracts#invite_users', as: 'contracts_invite'

  post 'answers/edit/all' => 'answers#edit_all', as: :answers_edit_all
  get 'answers/new', to: 'answers#new', as: 'new_answers'
  get 'answers/index'
  post 'answers' => 'answers#create'

  get 'decisions/new'
  get 'decisions/index'
  get 'decisions/edit' => 'decisions#edit'
  get 'decisions/show' => 'decisions#show'
  post 'decisions/edit' => 'decisions#update'
  post 'decisions/new' => 'decisions#create'
  delete 'decision/delete' => 'decisions#destroy'

end

app/models/answer.rb
class Answer < ApplicationRecord
  validates :user_id, presence: true
  validates :answer, presence: true
  validates :decision_id, presence: true

  belongs_to :decision
  belongs_to :user

  def self.find_all_names(type, answers, user)
    names = answers.where(answer: type).select {|a| a.viewable?(user)}.map {|a| a.user.users_name}
    names.join(", ")
  end

  def self.types
    types = ['Explain', 'Consult', 'Agree', 'Advise', 'Inquire']
  end

  def contract
    self.decision.contract
  end

  def viewable?(user)
    self.contract.reviewable || user_answer?(user) || self.contract.owner?(user) || self.contract.viewer?(user)
  end


  def user_answer?(user)
    self.user == user
  end


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @decision = Decision.find(params[:decision_id])
    @answer = Answer.new()
  end

  def create
    @answer = Answer.where(user_id: answer_params[:user_id], decision_id: answer_params[:decision_id]).first rescue nil
    if @answer.blank?
      @answer = Answer.new(answer_params)
    else
      @answer.update(answer_params)
    end

    if @answer.save
      redirect_to @answer.contract.path
    else
      @decision = @answer.decision
      render new_answers_path(@answer)
    end
  end


  private
  def answer_params
    params.require(:answer).permit(:user_id, :answer, :decision_id)
  end
end

app/views/answers/new.html.erb
<div class="new_answer">

  <h1 class="text-center"><%= @decision.description %></h1>

  <div class="container">
    <%= render 'shared/form_errors', object: @answer %>

    <%= form_for :answer, url: answers_path do |f| %>
      <%= f.hidden_field :user_id, :value => current_user.id, required: true %>
      <%= f.hidden_field :decision_id, :value => @decision.id %>
      <div class="row max-width-800 margin-auto margin-top-10">
        <div class="col-xs-1"></div>
        <% Answer.types.each do |type| %>
          <div class="col-xs-2 text-center">
            <%= f.label type %><br>
            <%= f.radio_button :answer,type, :checked => @decision.user_answer_type?(type, current_user), :required => "true"%>
          </div>
        <% end %>
      </div>
      <div class="submit-button max-width-600 margin-auto">
        <%= f.submit class: "btn btn-primary pull-right" %>

      </div>
    <% end %>
  </div>

</div>